/**
 * Quick Presets
 * 
 * Ready-made prompt combinations for specific use cases
 */

import type { Gender, JewelryType, BlockSelections } from './types';

export interface QuickPreset {
  id: string;
  name: string;
  description: string;
  thumbnail?: string;
  category: 'editorial' | 'ecommerce' | 'lifestyle' | 'luxury' | 'closeup' | 'casual';
  gender: Gender;
  jewelryType: JewelryType;
  selections: BlockSelections;
  tags: string[];
}

// ============================================
// WOMEN RING PRESETS
// ============================================

export const WOMEN_RING_PRESETS: QuickPreset[] = [
  {
    id: 'women-ring-classic-wedding',
    name: 'Classic Wedding Band',
    description: 'Traditional wedding ring on ring finger, elegant and timeless',
    category: 'ecommerce',
    gender: 'women',
    jewelryType: 'ring',
    selections: {
      'race-ethnicity': 'race-caucasian',
      'skin-tone': 'skin-light',
      'hand-selection': 'hand-left',
      'finger-selection': 'finger-ring',
      'hand-pose': 'hand-elegant',
      'hand-structure': 'hand-delicate',
      'nail-type': 'nail-french',
      'nail-color': 'nail-nude',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-white',
      'location-background': 'loc-studio-white',
      'lighting': 'light-studio-softbox',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-rule-thirds',
      'post-processing-level': 'proc-catalog',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-ecommerce',
      'mood-atmosphere': 'mood-elegant',
      'jewelry-context': 'context-hero',
    },
    tags: ['wedding', 'traditional', 'classic', 'elegant'],
  },
  
  {
    id: 'women-ring-luxury-editorial',
    name: 'Luxury Editorial',
    description: 'High-fashion editorial style with dramatic lighting',
    category: 'editorial',
    gender: 'women',
    jewelryType: 'ring',
    selections: {
      'race-ethnicity': 'race-mixed',
      'skin-tone': 'skin-olive',
      'hand-selection': 'hand-right',
      'finger-selection': 'finger-index',
      'hand-pose': 'hand-touching-face',
      'hand-structure': 'hand-graceful-wrist',
      'nail-type': 'nail-stiletto',
      'nail-color': 'nail-burgundy',
      'makeup': 'makeup-bold-lips',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-black',
      'location-background': 'loc-studio-black',
      'lighting': 'light-dramatic-low-key',
      'jewelry-framing': 'frame-medium-context',
      'viewing-angle': 'angle-side-profile',
      'focus-depth': 'focus-jewelry-model',
      'composition-rules': 'comp-golden-ratio',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-high-contrast',
      'presentation-intent': 'intent-editorial',
      'mood-atmosphere': 'mood-dramatic',
      'jewelry-context': 'context-balanced',
    },
    tags: ['luxury', 'editorial', 'dramatic', 'fashion'],
  },
  
  {
    id: 'women-ring-lifestyle-coffee',
    name: 'Lifestyle Café Moment',
    description: 'Casual lifestyle shot with coffee cup, warm and inviting',
    category: 'lifestyle',
    gender: 'women',
    jewelryType: 'ring',
    selections: {
      'race-ethnicity': 'race-hispanic',
      'skin-tone': 'skin-tan',
      'hand-selection': 'hand-right',
      'finger-selection': 'finger-ring',
      'hand-pose': 'hand-holding-cup',
      'hand-structure': 'hand-youthful',
      'nail-type': 'nail-round',
      'nail-color': 'nail-pink-soft',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-cream',
      'location-background': 'loc-lifestyle-cafe',
      'lighting': 'light-natural-window',
      'jewelry-framing': 'frame-lifestyle',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-jewelry-context-sharp',
      'composition-rules': 'comp-rule-thirds',
      'post-processing-level': 'proc-natural',
      'color-grading': 'grade-warm',
      'presentation-intent': 'intent-lifestyle',
      'mood-atmosphere': 'mood-romantic',
      'jewelry-context': 'context-lifestyle',
      'props-accessories': 'props-coffee',
    },
    tags: ['lifestyle', 'casual', 'coffee', 'warm'],
  },
  
  {
    id: 'women-ring-stacked-boho',
    name: 'Stacked Boho Rings',
    description: 'Multiple rings on different fingers, bohemian style',
    category: 'casual',
    gender: 'women',
    jewelryType: 'ring',
    selections: {
      'race-ethnicity': 'race-caucasian',
      'skin-tone': 'skin-fair',
      'hand-selection': 'hand-right',
      'finger-selection': 'finger-multiple',
      'hand-pose': 'hand-spread',
      'hand-structure': 'hand-long-fingers',
      'nail-type': 'nail-natural-short',
      'nail-color': 'nail-nude',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-beige',
      'location-background': 'loc-outdoor-garden',
      'lighting': 'light-natural-golden',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-light',
      'color-grading': 'grade-warm',
      'presentation-intent': 'intent-lifestyle',
      'mood-atmosphere': 'mood-playful',
      'jewelry-context': 'context-detail',
      'props-accessories': 'props-flowers',
    },
    tags: ['boho', 'stacked', 'multiple', 'casual'],
  },
  
  {
    id: 'women-ring-minimalist-catalog',
    name: 'Minimalist Catalog',
    description: 'Clean, simple catalog shot on white background',
    category: 'ecommerce',
    gender: 'women',
    jewelryType: 'ring',
    selections: {
      'race-ethnicity': 'race-asian',
      'skin-tone': 'skin-light',
      'hand-selection': 'hand-left',
      'finger-selection': 'finger-ring',
      'hand-pose': 'hand-relaxed',
      'hand-structure': 'hand-petite',
      'nail-type': 'nail-oval',
      'nail-color': 'nail-nude',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-white',
      'location-background': 'loc-studio-white',
      'lighting': 'light-studio-key-fill',
      'jewelry-framing': 'frame-detail',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-catalog',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-catalog',
      'mood-atmosphere': 'mood-minimalist',
      'jewelry-context': 'context-hero',
    },
    tags: ['minimalist', 'catalog', 'clean', 'white'],
  },
  
  {
    id: 'women-ring-extreme-closeup',
    name: 'Extreme Detail Close-Up',
    description: 'Ultra-close macro shot showing ring details',
    category: 'closeup',
    gender: 'women',
    jewelryType: 'ring',
    selections: {
      'skin-tone': 'skin-medium',
      'hand-selection': 'hand-right',
      'finger-selection': 'finger-ring',
      'hand-pose': 'hand-relaxed',
      'hand-structure': 'hand-smooth',
      'nail-type': 'nail-french',
      'nail-color': 'nail-pink-baby',
      'location-background': 'loc-abstract-bokeh',
      'lighting': 'light-studio-ring',
      'jewelry-framing': 'frame-extreme-closeup',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-catalog',
      'jewelry-context': 'context-detail',
    },
    tags: ['closeup', 'macro', 'detail', 'jewelry-focused'],
  },
];

// ============================================
// WOMEN NECKLACE PRESETS
// ============================================

export const WOMEN_NECKLACE_PRESETS: QuickPreset[] = [
  {
    id: 'women-necklace-elegant-portrait',
    name: 'Elegant Portrait',
    description: 'Close-up of necklace on neck with soft lighting',
    category: 'editorial',
    gender: 'women',
    jewelryType: 'necklace',
    selections: {
      'race-ethnicity': 'race-caucasian',
      'skin-tone': 'skin-light',
      'neck-area': 'neck-elegant',
      'makeup': 'makeup-natural',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-black',
      'location-background': 'loc-studio-grey',
      'lighting': 'light-studio-softbox',
      'jewelry-framing': 'frame-medium-context',
      'viewing-angle': 'angle-front-facing',
      'focus-depth': 'focus-jewelry-model',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-editorial',
      'mood-atmosphere': 'mood-elegant',
      'jewelry-context': 'context-hero',
    },
    tags: ['portrait', 'elegant', 'editorial', 'closeup'],
  },
  {
    id: 'women-necklace-luxury-editorial',
    name: 'Luxury Editorial',
    description: 'High-fashion look with dramatic lighting',
    category: 'editorial',
    gender: 'women',
    jewelryType: 'necklace',
    selections: {
      'race-ethnicity': 'race-mixed',
      'skin-tone': 'skin-olive',
      'neck-area': 'neck-long',
      'makeup': 'makeup-bold-lips',
      'upper-clothing': 'upper-strapless',
      'upper-color': 'upper-black',
      'location-background': 'loc-studio-black',
      'lighting': 'light-dramatic-low-key',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-side-profile',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-golden-ratio',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-high-contrast',
      'presentation-intent': 'intent-editorial',
      'mood-atmosphere': 'mood-dramatic',
      'jewelry-context': 'context-balanced',
    },
    tags: ['luxury', 'dramatic', 'fashion', 'editorial'],
  },
  {
    id: 'women-necklace-catalog-clean',
    name: 'Clean Catalog Shot',
    description: 'White background product shot for e-commerce',
    category: 'ecommerce',
    gender: 'women',
    jewelryType: 'necklace',
    selections: {
      'race-ethnicity': 'race-asian',
      'skin-tone': 'skin-light',
      'neck-area': 'neck-delicate',
      'makeup': 'makeup-minimal',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-white',
      'location-background': 'loc-studio-white',
      'lighting': 'light-studio-key-fill',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-front-facing',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-catalog',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-catalog',
      'mood-atmosphere': 'mood-minimalist',
      'jewelry-context': 'context-hero',
    },
    tags: ['catalog', 'clean', 'ecommerce', 'white'],
  },
  {
    id: 'women-necklace-lifestyle-casual',
    name: 'Lifestyle Casual',
    description: 'Natural lifestyle setting with warm tones',
    category: 'lifestyle',
    gender: 'women',
    jewelryType: 'necklace',
    selections: {
      'race-ethnicity': 'race-hispanic',
      'skin-tone': 'skin-tan',
      'neck-area': 'neck-natural',
      'makeup': 'makeup-natural',
      'upper-clothing': 'upper-vneck',
      'upper-color': 'upper-cream',
      'location-background': 'loc-lifestyle-cafe',
      'lighting': 'light-natural-window',
      'jewelry-framing': 'frame-lifestyle',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-jewelry-context-sharp',
      'composition-rules': 'comp-rule-thirds',
      'post-processing-level': 'proc-natural',
      'color-grading': 'grade-warm',
      'presentation-intent': 'intent-lifestyle',
      'mood-atmosphere': 'mood-romantic',
      'jewelry-context': 'context-lifestyle',
    },
    tags: ['lifestyle', 'casual', 'warm', 'natural'],
  },
  {
    id: 'women-necklace-layered-boho',
    name: 'Layered Boho Style',
    description: 'Multiple necklaces in bohemian setting',
    category: 'casual',
    gender: 'women',
    jewelryType: 'necklace',
    selections: {
      'race-ethnicity': 'race-caucasian',
      'skin-tone': 'skin-fair',
      'neck-area': 'neck-natural',
      'makeup': 'makeup-minimal',
      'upper-clothing': 'upper-off-shoulder',
      'upper-color': 'upper-beige',
      'location-background': 'loc-outdoor-garden',
      'lighting': 'light-natural-golden',
      'jewelry-framing': 'frame-medium-context',
      'viewing-angle': 'angle-front-facing',
      'focus-depth': 'focus-jewelry-model',
      'composition-rules': 'comp-rule-thirds',
      'post-processing-level': 'proc-light',
      'color-grading': 'grade-warm',
      'presentation-intent': 'intent-lifestyle',
      'mood-atmosphere': 'mood-playful',
      'jewelry-context': 'context-lifestyle',
    },
    tags: ['boho', 'layered', 'outdoor', 'golden-hour'],
  },
];

// ============================================
// WOMEN EARRING PRESETS
// ============================================

export const WOMEN_EARRING_PRESETS: QuickPreset[] = [
  {
    id: 'women-earring-elegant-profile',
    name: 'Elegant Profile',
    description: 'Side profile showing earring with clean background',
    category: 'editorial',
    gender: 'women',
    jewelryType: 'earring',
    selections: {
      'race-ethnicity': 'race-caucasian',
      'skin-tone': 'skin-light',
      'ear-area': 'ear-visible',
      'hair-style': 'hair-updo',
      'makeup': 'makeup-natural',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-black',
      'location-background': 'loc-studio-grey',
      'lighting': 'light-studio-softbox',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-side-profile',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-rule-thirds',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-editorial',
      'mood-atmosphere': 'mood-elegant',
      'jewelry-context': 'context-hero',
    },
    tags: ['profile', 'elegant', 'editorial', 'updo'],
  },
  {
    id: 'women-earring-drop-dramatic',
    name: 'Drop Earring Drama',
    description: 'Dramatic lighting for statement drop earrings',
    category: 'editorial',
    gender: 'women',
    jewelryType: 'earring',
    selections: {
      'race-ethnicity': 'race-african',
      'skin-tone': 'skin-dark',
      'ear-area': 'ear-prominent',
      'hair-style': 'hair-short',
      'makeup': 'makeup-bold-lips',
      'upper-clothing': 'upper-strapless',
      'upper-color': 'upper-black',
      'location-background': 'loc-studio-black',
      'lighting': 'light-dramatic-low-key',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-three-quarter',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-golden-ratio',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-high-contrast',
      'presentation-intent': 'intent-editorial',
      'mood-atmosphere': 'mood-dramatic',
      'jewelry-context': 'context-balanced',
    },
    tags: ['dramatic', 'drop', 'statement', 'editorial'],
  },
  {
    id: 'women-earring-stud-catalog',
    name: 'Stud Earring Catalog',
    description: 'Clean e-commerce shot for stud earrings',
    category: 'ecommerce',
    gender: 'women',
    jewelryType: 'earring',
    selections: {
      'race-ethnicity': 'race-asian',
      'skin-tone': 'skin-light',
      'ear-area': 'ear-visible',
      'hair-style': 'hair-behind-ear',
      'makeup': 'makeup-minimal',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-white',
      'location-background': 'loc-studio-white',
      'lighting': 'light-studio-key-fill',
      'jewelry-framing': 'frame-detail',
      'viewing-angle': 'angle-side-profile',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-catalog',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-catalog',
      'mood-atmosphere': 'mood-minimalist',
      'jewelry-context': 'context-hero',
    },
    tags: ['stud', 'catalog', 'clean', 'ecommerce'],
  },
  {
    id: 'women-earring-hoop-lifestyle',
    name: 'Hoop Earring Lifestyle',
    description: 'Casual lifestyle shot with hoop earrings',
    category: 'lifestyle',
    gender: 'women',
    jewelryType: 'earring',
    selections: {
      'race-ethnicity': 'race-hispanic',
      'skin-tone': 'skin-tan',
      'ear-area': 'ear-visible',
      'hair-style': 'hair-flowing',
      'makeup': 'makeup-natural',
      'upper-clothing': 'upper-casual',
      'upper-color': 'upper-denim',
      'location-background': 'loc-lifestyle-urban',
      'lighting': 'light-natural-window',
      'jewelry-framing': 'frame-lifestyle',
      'viewing-angle': 'angle-three-quarter',
      'focus-depth': 'focus-jewelry-context-sharp',
      'composition-rules': 'comp-rule-thirds',
      'post-processing-level': 'proc-natural',
      'color-grading': 'grade-warm',
      'presentation-intent': 'intent-lifestyle',
      'mood-atmosphere': 'mood-playful',
      'jewelry-context': 'context-lifestyle',
    },
    tags: ['hoop', 'lifestyle', 'casual', 'urban'],
  },
  {
    id: 'women-earring-macro-detail',
    name: 'Macro Detail Shot',
    description: 'Extreme close-up showing earring details',
    category: 'closeup',
    gender: 'women',
    jewelryType: 'earring',
    selections: {
      'skin-tone': 'skin-medium',
      'ear-area': 'ear-prominent',
      'hair-style': 'hair-behind-ear',
      'location-background': 'loc-abstract-bokeh',
      'lighting': 'light-studio-ring',
      'jewelry-framing': 'frame-extreme-closeup',
      'viewing-angle': 'angle-side-profile',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-catalog',
      'jewelry-context': 'context-detail',
    },
    tags: ['macro', 'detail', 'closeup', 'professional'],
  },
];

// ============================================
// WOMEN BRACELET PRESETS
// ============================================

export const WOMEN_BRACELET_PRESETS: QuickPreset[] = [
  {
    id: 'women-bracelet-elegant-wrist',
    name: 'Elegant Wrist Shot',
    description: 'Clean shot of bracelet on elegant wrist',
    category: 'ecommerce',
    gender: 'women',
    jewelryType: 'bracelet',
    selections: {
      'race-ethnicity': 'race-caucasian',
      'skin-tone': 'skin-light',
      'hand-selection': 'hand-left',
      'hand-pose': 'hand-relaxed',
      'hand-structure': 'hand-delicate',
      'nail-type': 'nail-oval',
      'nail-color': 'nail-nude',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-white',
      'location-background': 'loc-studio-white',
      'lighting': 'light-studio-softbox',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-catalog',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-catalog',
      'mood-atmosphere': 'mood-elegant',
      'jewelry-context': 'context-hero',
    },
    tags: ['wrist', 'elegant', 'catalog', 'clean'],
  },
  {
    id: 'women-bracelet-stacked-luxury',
    name: 'Stacked Bracelets Luxury',
    description: 'Multiple bracelets stacked on wrist',
    category: 'luxury',
    gender: 'women',
    jewelryType: 'bracelet',
    selections: {
      'race-ethnicity': 'race-mixed',
      'skin-tone': 'skin-olive',
      'hand-selection': 'hand-right',
      'hand-pose': 'hand-elegant',
      'hand-structure': 'hand-graceful-wrist',
      'nail-type': 'nail-almond',
      'nail-color': 'nail-burgundy',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-black',
      'location-background': 'loc-studio-grey',
      'lighting': 'light-dramatic-low-key',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-side-profile',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-golden-ratio',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-high-contrast',
      'presentation-intent': 'intent-editorial',
      'mood-atmosphere': 'mood-dramatic',
      'jewelry-context': 'context-balanced',
    },
    tags: ['stacked', 'luxury', 'multiple', 'editorial'],
  },
  {
    id: 'women-bracelet-lifestyle-coffee',
    name: 'Lifestyle Coffee Moment',
    description: 'Bracelet visible while holding coffee cup',
    category: 'lifestyle',
    gender: 'women',
    jewelryType: 'bracelet',
    selections: {
      'race-ethnicity': 'race-hispanic',
      'skin-tone': 'skin-tan',
      'hand-selection': 'hand-right',
      'hand-pose': 'hand-holding-cup',
      'hand-structure': 'hand-youthful',
      'nail-type': 'nail-round',
      'nail-color': 'nail-pink-soft',
      'upper-clothing': 'upper-sweater',
      'upper-color': 'upper-cream',
      'location-background': 'loc-lifestyle-cafe',
      'lighting': 'light-natural-window',
      'jewelry-framing': 'frame-lifestyle',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-jewelry-context-sharp',
      'composition-rules': 'comp-rule-thirds',
      'post-processing-level': 'proc-natural',
      'color-grading': 'grade-warm',
      'presentation-intent': 'intent-lifestyle',
      'mood-atmosphere': 'mood-romantic',
      'jewelry-context': 'context-lifestyle',
      'props-accessories': 'props-coffee',
    },
    tags: ['lifestyle', 'coffee', 'casual', 'warm'],
  },
  {
    id: 'women-bracelet-bangle-editorial',
    name: 'Bangle Editorial',
    description: 'Fashion editorial style bangle photography',
    category: 'editorial',
    gender: 'women',
    jewelryType: 'bracelet',
    selections: {
      'race-ethnicity': 'race-african',
      'skin-tone': 'skin-dark',
      'hand-selection': 'hand-left',
      'hand-pose': 'hand-touching-face',
      'hand-structure': 'hand-long-fingers',
      'nail-type': 'nail-stiletto',
      'nail-color': 'nail-gold',
      'upper-clothing': 'upper-plain',
      'upper-color': 'upper-gold',
      'location-background': 'loc-studio-black',
      'lighting': 'light-studio-ring',
      'jewelry-framing': 'frame-medium-context',
      'viewing-angle': 'angle-three-quarter',
      'focus-depth': 'focus-jewelry-model',
      'composition-rules': 'comp-golden-ratio',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-warm',
      'presentation-intent': 'intent-editorial',
      'mood-atmosphere': 'mood-dramatic',
      'jewelry-context': 'context-balanced',
    },
    tags: ['bangle', 'editorial', 'fashion', 'dramatic'],
  },
  {
    id: 'women-bracelet-charm-detail',
    name: 'Charm Bracelet Detail',
    description: 'Close-up detail shot of charm bracelet',
    category: 'closeup',
    gender: 'women',
    jewelryType: 'bracelet',
    selections: {
      'skin-tone': 'skin-medium',
      'hand-selection': 'hand-left',
      'hand-pose': 'hand-relaxed',
      'hand-structure': 'hand-smooth',
      'nail-type': 'nail-french',
      'nail-color': 'nail-pink-baby',
      'location-background': 'loc-abstract-bokeh',
      'lighting': 'light-studio-softbox',
      'jewelry-framing': 'frame-extreme-closeup',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-catalog',
      'jewelry-context': 'context-detail',
    },
    tags: ['charm', 'detail', 'closeup', 'macro'],
  },
];

// ============================================
// MEN RING PRESETS
// ============================================

export const MEN_RING_PRESETS: QuickPreset[] = [
  {
    id: 'men-ring-wedding-band',
    name: 'Classic Wedding Band',
    description: 'Traditional men\'s wedding band shot',
    category: 'ecommerce',
    gender: 'men',
    jewelryType: 'ring',
    selections: {
      'race-ethnicity': 'race-caucasian',
      'skin-tone': 'skin-medium',
      'hand-selection': 'hand-left',
      'finger-selection': 'finger-ring',
      'hand-pose': 'hand-relaxed',
      'hand-structure': 'hand-masculine',
      'nail-type': 'nail-natural-short',
      'upper-clothing': 'upper-suit',
      'upper-color': 'upper-navy',
      'location-background': 'loc-studio-grey',
      'lighting': 'light-studio-softbox',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-centered',
      'post-processing-level': 'proc-catalog',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-catalog',
      'mood-atmosphere': 'mood-elegant',
      'jewelry-context': 'context-hero',
    },
    tags: ['wedding', 'classic', 'masculine', 'elegant'],
  },
  {
    id: 'men-ring-signet-luxury',
    name: 'Signet Ring Luxury',
    description: 'Luxury signet ring editorial shot',
    category: 'editorial',
    gender: 'men',
    jewelryType: 'ring',
    selections: {
      'race-ethnicity': 'race-mixed',
      'skin-tone': 'skin-olive',
      'hand-selection': 'hand-right',
      'finger-selection': 'finger-pinky',
      'hand-pose': 'hand-clenched',
      'hand-structure': 'hand-masculine',
      'nail-type': 'nail-natural-short',
      'upper-clothing': 'upper-leather',
      'upper-color': 'upper-black',
      'location-background': 'loc-studio-black',
      'lighting': 'light-dramatic-low-key',
      'jewelry-framing': 'frame-closeup',
      'viewing-angle': 'angle-side-profile',
      'focus-depth': 'focus-sharp-jewelry',
      'composition-rules': 'comp-golden-ratio',
      'post-processing-level': 'proc-professional',
      'color-grading': 'grade-high-contrast',
      'presentation-intent': 'intent-editorial',
      'mood-atmosphere': 'mood-dramatic',
      'jewelry-context': 'context-balanced',
    },
    tags: ['signet', 'luxury', 'dramatic', 'editorial'],
  },
  {
    id: 'men-ring-lifestyle-casual',
    name: 'Casual Lifestyle',
    description: 'Natural lifestyle setting for men\'s ring',
    category: 'lifestyle',
    gender: 'men',
    jewelryType: 'ring',
    selections: {
      'race-ethnicity': 'race-african',
      'skin-tone': 'skin-dark',
      'hand-selection': 'hand-right',
      'finger-selection': 'finger-index',
      'hand-pose': 'hand-relaxed',
      'hand-structure': 'hand-strong',
      'nail-type': 'nail-natural-short',
      'upper-clothing': 'upper-casual',
      'upper-color': 'upper-denim',
      'location-background': 'loc-lifestyle-urban',
      'lighting': 'light-natural-window',
      'jewelry-framing': 'frame-lifestyle',
      'viewing-angle': 'angle-eye-level',
      'focus-depth': 'focus-jewelry-context-sharp',
      'composition-rules': 'comp-rule-thirds',
      'post-processing-level': 'proc-natural',
      'color-grading': 'grade-natural',
      'presentation-intent': 'intent-lifestyle',
      'mood-atmosphere': 'mood-confident',
      'jewelry-context': 'context-lifestyle',
    },
    tags: ['casual', 'lifestyle', 'urban', 'natural'],
  },
];

// ============================================
// EXPORT ALL PRESETS BY TYPE
// ============================================

export const QUICK_PRESETS_BY_TYPE = {
  women: {
    ring: WOMEN_RING_PRESETS,
    necklace: WOMEN_NECKLACE_PRESETS,
    earring: WOMEN_EARRING_PRESETS,
    bracelet: WOMEN_BRACELET_PRESETS,
  },
  men: {
    ring: MEN_RING_PRESETS,
    necklace: [], // Coming soon
    earring: [], // Coming soon
    bracelet: [], // Coming soon
  },
};

export function getQuickPresets(gender: Gender, jewelryType: JewelryType): QuickPreset[] {
  return QUICK_PRESETS_BY_TYPE[gender]?.[jewelryType] || [];
}


